Convert most containers to use common compilation container (#6)
Converting the existing containers to use a common compilation container with pre-built libraries and standard compilers.

This effort also re-arranged the common directory structure of the different software and data containers. Now rather than a large number of top-level directories containing software, data, and scripts, the data that is not part of the operating system can now be found in three top-level directories:

/comsoftware - contains software packages that are built in each container (e.g. /comsoftware/wrf, /comsoftware/met), as well as libraries that are specific to community software (e.g. netCDF, BUFRLIB) which are built in the common compilation container under /comsoftware/libs
/data - contains input data for different packages. Data containers will be mounted here.
/home - contains scripts and working directories for each piece of software. Working directories (e.g. wpsprd, wrfprd, gsiprd, etc.) will be mounted here.
I also standardized the container permissions into a user known as 'comuser', rather than always running as root. This is considered best practice for security purposes (https://opensource.com/article/18/3/just-say-no-root-containers). This user has write permissions under /home, /comsoftware, and /data.

Runtime instructions needed to be changed for this new directory structure, and can be found in the updated README files.

diff --git a/components/gsi/Dockerfile b/components/gsi/Dockerfile
--- a/components/gsi/Dockerfile
+++ b/components/gsi/Dockerfile
@@ -1,86 +1,66 @@
-FROM ubuntu:latest
+FROM mkavulich/common-community-container:gnu7
 MAINTAINER Michael Kavulich <kavulich@ucar.edu>
 #
 # This Dockerfile compiles GSI from source during "docker build" step
+USER comuser
+RUN mkdir /comsoftware/gsi
+WORKDIR /comsoftware/gsi
 ENV GSI_VERSION 3.7
 ENV ENKF_VERSION 1.3
 
 # Make with this many parallel tasks
 ENV J 4
 
-#SERIAL BUILD
-RUN apt update
-#RUN yum -y install file gcc gcc-gfortran gcc-c++ glibc.i686 libgcc.i686 libpng-devel jasper jasper-devel ksh hostname m4 make perl tar tcsh time wget which zlib zlib-devel epel-release
-RUN apt -y install file gcc gfortran g++ ksh hostname m4 make perl tar tcsh time wget libopenmpi-dev libnetcdf-dev libnetcdff-dev netcdf-bin libopenblas-dev cmake vim emacs nano
-#
-# now get 3rd party EPEL builds of netcdf dependencies, hdf5, openmpi stuff, cmake3, and openblas
-#RUN apt install netcdf-openmpi-devel.x86_64 netcdf-fortran-openmpi-devel.x86_64 netcdf-fortran-openmpi.x86_64 hdf5-openmpi.x86_64 openmpi.x86_64 openmpi-devel.x86_64 cmake3 openblas-devel.x86_64
-#
-
-#
-WORKDIR /gsi
-#
 # Download source code
 #
-# This command will be used after the official release
-#RUN wget https://dtcenter.org/com-GSI/users/downloads/GSI_releases/comGSIv${GSI_VERSION}_EnKFv${ENKF_VERSION}.tar.gz | tar zxC /gsi 
-RUN wget https://dtcenter.org/com-GSI/users/downloads/GSI_releases/comGSIv3.7_EnKFv1.3.tar.gz 
-RUN tar -xvf comGSIv3.7_EnKFv1.3.tar.gz 
-#
-#ADD comGSIv${GSI_VERSION}_EnKFv${ENKF_VERSION}.tar.gz /gsi
-
+#RUN wget https://dtcenter.org/com-GSI/users/downloads/GSI_releases/comGSIv${GSI_VERSION}_EnKFv${ENKF_VERSION}.tar.gz | tar zxC /comsoftware/gsi 
+RUN curl -SL https://dtcenter.org/com-GSI/users/downloads/GSI_releases/comGSIv${GSI_VERSION}_EnKFv${ENKF_VERSION}.tar.gz | tar -xzC /comsoftware/gsi
 # Set necessary environment variables for GSI build
 #
 ENV LDFLAGS -lm
-ENV NETCDF /gsi/netcdf_links
-ENV LD_LIBRARY_PATH /usr/lib/
+ENV NETCDF /comsoftware/libs/netcdf/
+ENV LD_LIBRARY_PATH /usr/lib:/comsoftware/libs/netcdf/lib
 ENV PATH /usr/lib64/openmpi/bin:$PATH
 ENV HDF5_ROOT $NETCDF
-ENV WE_ARE_IN_THE_GSI_CONTAINER true
 #
-# Build GSI
+# Prep GSI build
 # 
 RUN pwd \ 
  && env \
- && mkdir netcdf_links \
- && ln -sf /usr/include /gsi/netcdf_links/ \
- && ln -sf /usr/lib/x86_64-linux-gnu/ /gsi/netcdf_links/lib \
- && mkdir gsi_build \
- && cd gsi_build \
- && cmake /gsi/comGSIv${GSI_VERSION}_EnKFv${ENKF_VERSION} \
- && make -j ${J}
+ && mkdir /comsoftware/gsi/gsi_build \
+ && cd /comsoftware/gsi/gsi_build \
+ && cmake /comsoftware/gsi/comGSIv${GSI_VERSION}_EnKFv${ENKF_VERSION} 
+
+#
+# Fix a few GSI bugs
+#
+RUN sed -i 's/wij(1)/wij/g' /comsoftware/gsi/comGSIv3.7_EnKFv1.3/src/setuplight.f90 \
+ && sed -i 's/$/ -L\/comsoftware\/libs\/netcdf\/lib/g' /comsoftware/gsi/gsi_build/src/CMakeFiles/gsi.x.dir/link.txt \
+ && sed -i 's/$/ -L\/comsoftware\/libs\/netcdf\/lib/g' /comsoftware/gsi/gsi_build/src/enkf/CMakeFiles/enkf_wrf.x.dir/link.txt
+#
+# Build GSI
+#
+RUN cd /comsoftware/gsi/gsi_build \
+ && make -j ${J} || echo "I think your build failed yo!"
 #
 # Setup run directory
-RUN mkdir /gsi/gsi_run
-#
-# Set some useful settings for bashrc/cshrc
-RUN echo set -o ignoreeof >> /etc/bashrc \
- && echo set -o ignoreeof >> /etc/csh.cshrc \
-RUN set -o ignoreeof
-#
-# copy in a couple custom scripts
-#
-#COPY docker-clean /gsi
-COPY run-gsi /gsi/gsi_run
-#RUN chmod +x /gsi/docker-clean \
-# && chmod +x /gsi/gsi_run/run-gsi
+RUN mkdir /home/gsi_run
 #
 # set up ssh configuration
 #
-COPY ssh_config /root/.ssh/config
-COPY slave /gsi/slave
-RUN apt install -y openssh-client openssh-server net-tools \
-    && apt clean all \
-    && mkdir -p /var/run/sshd \
-    && ssh-keygen -A \
-    && sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config \
-    && sed -i 's/#RSAAuthentication yes/RSAAuthentication yes/g' /etc/ssh/sshd_config \
-    && sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config \
-    && ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' \
-    && chmod 600 /root/.ssh/config \
-    && chmod 700 /root/.ssh \
-    && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys \
-    && chmod +x /gsi/slave
+#COPY ssh_config /root/.ssh/config
+#COPY slave /gsi/slave
+#RUN apt install -y openssh-client openssh-server net-tools \
+#    && apt clean all \
+#    && mkdir -p /var/run/sshd \
+#    && ssh-keygen -A \
+#    && sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config \
+#    && sed -i 's/#RSAAuthentication yes/RSAAuthentication yes/g' /etc/ssh/sshd_config \
+#    && sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config \
+#    && ssh-keygen -f /root/.ssh/id_rsa -t rsa -N '' \
+#    && chmod 600 /root/.ssh/config \
+#    && chmod 700 /root/.ssh \
+#    && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys \
+#    && chmod +x /gsi/slave
 #
-#RUN env
-CMD ["/gsi/run-gsi"]
+CMD ["/home/gsiprd/run-gsi"]
