change the value of url.output #93 (#95)
* change the value of url.output #93

* Update METviewer to 4.1, METcalcpy/plotpy to 1.1 and add METdatadb 1.1 to fix Python libtary dependencies #93

* fixed parameters replacement in METviewer scripts #93

* change mapping port to Tomcat to 8080 #93

* add port 8080 to the new URL #93

* fix db host by changing the value to mysql_mv #93

* add docker-compose version #93

* use latest image #93

* add the version number  #93

* remove files that are not needed  #93

diff --git a/components/metviewer/METviewer/Dockerfile b/components/metviewer/METviewer/Dockerfile
--- a/components/metviewer/METviewer/Dockerfile
+++ b/components/metviewer/METviewer/Dockerfile
@@ -5,9 +5,10 @@ MAINTAINER Tatiana Burek <tatiana@ucar.edu>
 #
 # This Dockerfile checks out METviewer from GitHub and builds the specified branch or tag.
 #
-ENV METVIEWER_GIT_NAME v4.0.2
-ENV METCALCPY_GIT_NAME v1.0.0
-ENV METPLOTPY_GIT_NAME v1.0.0
+ENV METVIEWER_GIT_NAME v4.1.0
+ENV METCALCPY_GIT_NAME v1.1.0
+ENV METPLOTPY_GIT_NAME v1.1.0
+ENV METDATADB_GIT_NAME v1.1.0
 
 #
 # Constants
@@ -19,6 +20,8 @@ ENV TOMCAT_VERSION ${TOMCAT_MAJOR_VERSION}.${TOMCAT_MINOR_VERSION}
 ENV METVIEWER_GIT_URL  https://github.com/dtcenter/METviewer
 ENV METCALCPY_GIT_URL  https://github.com/dtcenter/METcalcpy
 ENV METPLOTPY_GIT_URL  https://github.com/dtcenter/METplotpy
+ENV METDATADB_GIT_URL  https://github.com/dtcenter/METdataio
+
 
 ENV UMASK 002
 
@@ -50,6 +53,16 @@ RUN if [ "x${METPLOTPY_GIT_NAME}" = "x" ]; then \
       exit 1; \
     else \
       echo "Build Argument METPLOTPY_GIT_NAME=${METPLOTPY_GIT_NAME}"; \
+    fi
+
+#
+# METDATADB_GIT_NAME is required.
+#
+RUN if [ "x${METDATADB_GIT_NAME}" = "x" ]; then \
+      echo "ERROR: METDATADB_GIT_NAME undefined! Rebuild with \"--build-arg METDATADB_GIT_NAME={branch, tag, or hash}\""; \
+      exit 1; \
+    else \
+      echo "Build Argument METDATADB_GIT_NAME=${METDATADB_GIT_NAME}"; \
     fi
 
 #
@@ -116,7 +129,11 @@ RUN mkdir /METviewer-python \
  && echo "Checking out METplotpy ${METPLOTPY_GIT_NAME} from ${METPLOTPY_GIT_URL}" \
  && git clone ${METPLOTPY_GIT_URL} /METviewer-python/METplotpy \
  && cd /METviewer-python/METplotpy \
- && git checkout ${METPLOTPY_NAME_TAG}
+ && git checkout ${METPLOTPY_NAME_TAG} \
+ && echo "Checking out METdatadb ${METDATADB_GIT_NAME} from ${METDATADB_GIT_NAME}" \
+ && git clone ${METDATADB_GIT_URL} /METviewer-python/METdatadb \
+ && cd /METviewer-python/METdatadb \
+ && git checkout ${METDATADB_NAME_TAG}
 
 #
 # Install METviewer
@@ -126,7 +143,7 @@ RUN echo "Checking out METviewer ${METVIEWER_GIT_NAME} from ${METVIEWER_GIT_URL}
  && cd /METviewer \
  && git checkout ${METVIEWER_GIT_NAME} \
  && echo "Configuring and building METviewer" \
- && cd /METviewer \ 
+ && cd /METviewer \
  && cat webapp/metviewer/WEB-INF/classes/build.properties | \
     sed -r 's%db.host=.*%db.host=mysql_mv%g' | \
     sed -r 's%db.user=.*%db.user=root%g' | \
@@ -134,48 +151,37 @@ RUN echo "Checking out METviewer ${METVIEWER_GIT_NAME} from ${METVIEWER_GIT_URL}
     sed -r 's%db.management.system=.*%db.management.system=mysql%g' | \
     sed -r 's%output.dir=.*%output.dir=/opt/tomcat/webapps/metviewer_output/%g' | \
     sed -r 's%webapps.dir=.*%webapps.dir=/opt/tomcat/webapps/metviewer/%g' | \
-    sed -r 's%url.output=.*%url.output=http://localhost:8080/metviewer_output/%g' | \
+    sed -r 's%url.output=.*%url.output=/metviewer_output/%g' | \
     sed -r 's%python.env=.*%python.env=/usr/local/%g' | \
     sed -r 's%metcalcpy.home=.*%metcalcpy.home=/METviewer-python/METcalcpy/%g' | \
-    sed -r 's%metplotpy.home=.*%metplotpy.home=/METviewer-python/METplotpy/metplotpy/%g' \
+    sed -r 's%metdatadb.home=.*%metdatadb.home=/METviewer-python/METdatadb/%g' | \
+    sed -r 's%metplotpy.home=.*%metplotpy.home=/METviewer-python/METplotpy/%g' \
     > build.properties \
  && ant -Dbuild.properties.file=./build.properties \
         -Ddb.management.system=mariadb \
         -Dmetcalcpy.path=/METviewer-python/METcalcpy/ \
+        -Dmetdatadb.path=/METviewer-python/METdatadb/ \
         -Dmetplotpy.path=/METviewer-python/METplotpy/ \
         -Dpython.env.path=/usr/local/ war \
  && mv /METviewer/dist/*.war ${CATALINA_HOME}/webapps \
  && echo "Configuring METviewer scripts" \
  && cd /METviewer/bin \
  && cat mv_batch.sh | \
-    sed -r 's%JAVA=.*%JAVA=java\nMV_HOME=/METviewer%g' | \
-    sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
-    sed -r 's%METCALCPY_HOME=.*%METCALCPY_HOME=/METviewer-python/METcalcpy/%g' | \
-    sed -r 's%METPLOTPY_HOME=.*%METPLOTPY_HOME=/METviewer-python/METplotpy/metplotpy/%g' \
-    >  mv_batch.sh-DOCKER \
- && mv mv_batch.sh-DOCKER mv_batch.sh \
- && cat mv_load.sh | \
-    sed -r 's%JAVA=.*%JAVA=java\nMV_HOME=/METviewer%g' | \
-    sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
-    sed -r 's%METCALCPY_HOME=.*%METCALCPY_HOME=/METviewer-python/METcalcpy/%g' | \
-    sed -r 's%METPLOTPY_HOME=.*%METPLOTPY_HOME=/METviewer-python/METplotpy/metplotpy/%g' \
-    >  mv_load.sh-DOCKER \
- && mv mv_load.sh-DOCKER mv_load.sh \
- && cat mv_scorecard.sh | \
-    sed -r 's%JAVA=.*%JAVA=java\nMV_HOME=/METviewer%g' | \
-    sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
-    sed -r 's%METCALCPY_HOME=.*%METCALCPY_HOME=/METviewer-python/METcalcpy/%g' | \
-    sed -r 's%METPLOTPY_HOME=.*%METPLOTPY_HOME=/METviewer-python/METplotpy/metplotpy/%g' \
-    >  mv_scorecard.sh-DOCKER \
- && mv mv_scorecard.sh-DOCKER mv_scorecard.sh \
- && cat mv_prune.sh | \
-    sed -r 's%JAVA=.*%JAVA=java\nMV_HOME=/METviewer%g' | \
-    sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
-    sed -r 's%METCALCPY_HOME=.*%METCALCPY_HOME=/METviewer-python/METcalcpy/%g' | \
-    sed -r 's%METPLOTPY_HOME=.*%METPLOTPY_HOME=/METviewer-python/METplotpy/metplotpy/%g' \
-    >  mv_prune.sh-DOCKER \
- && mv mv_prune.sh-DOCKER mv_prune.sh
-
+     sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
+     sed -r 's%METCALCPY_HOME=.*%METCALCPY_HOME=/METviewer-python/METcalcpy/%g' | \
+     sed -r 's%METPLOTPY_HOME=.*%METPLOTPY_HOME=/METviewer-python/METplotpy/%g'  \
+     >  mv_batch.sh-DOCKER \
+&& mv mv_batch.sh-DOCKER mv_batch.sh \
+&& cat mv_load.sh | \
+     sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
+     sed -r 's%METDATADB_HOME=.*%METDATADB_HOME=/METviewer-python/METdatadb/%g'  \
+     >  mv_load.sh-DOCKER \
+&& mv mv_load.sh-DOCKER mv_load.sh \
+&& cat mv_scorecard.sh | \
+     sed -r 's%PYTHON_ENV=.*%PYTHON_ENV=/usr/local%g' | \
+     sed -r 's%METCALCPY_HOME=.*%METCALCPY_HOME=/METviewer-python/METcalcpy/%g'  \
+     >  mv_scorecard.sh-DOCKER \
+&& mv mv_scorecard.sh-DOCKER mv_scorecard.sh
 #
 # Install Python 3.6
 #
@@ -185,20 +191,21 @@ RUN yum install -y python3 python3-devel python3-pip
 # Install Python packages
 #
 RUN pip-3 install kiwisolver==1.0.1 \
- && pip-3 install pillow==7.2.0 \
- && pip-3 install bootstrapped==0.0.2 \
  && pip-3 install plotly==4.9.0 \
  && pip-3 install kaleido==0.2.1 \
  && pip-3 install pandas==1.0.1 \
  && pip-3 install numpy==1.17.0 \
  && pip-3 install scipy==1.5.1 \
- && pip-3 install pingouin==0.3.8 \
  && pip-3 install PyYAML==5.3.1 \
  && pip-3 install psutil==5.7.2 \
- && pip-3 install requests==2.24.0 \
+ && pip-3 install requests \
+ && pip-3 install pillow==7.2.0 \
  && pip-3 install matplotlib==3.3.0 \
- && pip-3 install lxml==4.5.2 \
- && pip-3 install pymysql==0.9.3
+ && pip-3 install lxml \
+ && pip-3 install pymysql \
+ && pip-3 install retrying \
+ && pip-3 install cython \
+ && pip-3 install statsmodels==0.11.1
 
 #
 # Create a link for python3
